regioes_macro = {
    "america do sul": ["brasil", "peru", "argentina", "venezuela"],
    "america do norte":["alaska", "mackenzie", "vancouver", "ottawa", "labrador", "nova_york", "california", "mexico", "groelandia"],
    "europa":["islandia", "inglaterra", "frança", "alemanha", "polonia", "moscou", "suecia"],
    "asia":["oriente_medio", "aral", "omsk", "dudinka", "tchita", "siberia", "mongolia", "china", "japao", "vietna", "india", "vladvostok"],
    "africa":["argelia", "congo", "africa_do_sul", "madagascar", "sudao", "egito"],
    "oceania":["australia", "sumatra", "borneo", "nova_guine"]
}

fronteiras = {
    'alaska': ['vladvostok', 'mackenzie', 'vancouver'],
    'vladvostok': ['alaska', 'china', 'tchita', 'siberia', 'japao'],
    'mackenzie': ['alaska', 'vancouver', 'groelandia'],
    'vancouver': ['alaska', 'mackenzie', 'ottawa', 'california'],
    'ottawa': ['vancouver', 'california', 'nova_york', 'labrador'],
    'california': ['vancouver', 'ottawa', 'nova_york', 'mexico'],
    'groelandia': ['mackenzie', 'labrador', 'islandia'],
    'nova_york': ['ottawa', 'california', 'mexico', 'labrador'],
    'labrador': ['ottawa', 'nova_york', 'groelandia'],
    'mexico': ['california', 'nova_york', 'venezuela'],
    'venezuela': ['mexico', 'peru', 'brasil'],
    'peru': ['venezuela', 'brasil', 'argentina'],
    'brasil': ['venezuela', 'peru', 'argentina', 'argelia'],
    'argentina': ['peru', 'brasil'],
    'argelia': ['brasil', 'frança', 'egito', 'sudao', 'congo'],
    'frança': ['argelia', 'egito', 'alemanha', 'polonia', 'inglaterra'],
    'egito': ['argelia', 'sudao', 'frança', 'oriente_medio', 'polonia'],
    'sudao': ['argelia', 'egito', 'congo', 'madagascar', 'africa_do_sul'],
    'congo': ['argelia', 'sudao', 'africa_do_sul'],
    'madagascar': ['sudao', 'africa_do_sul'],
    'africa_do_sul': ['sudao', 'madagascar', 'congo'],
    'oriente_medio': ['egito', 'moscou', 'polonia', 'aral', 'india'],
    'polonia': ['egito', 'frança', 'alemanha', 'moscou', 'oriente_medio'],
    'alemanha': ['frança', 'polonia', 'inglaterra'],
    'inglaterra': ['frança', 'alemanha', 'islandia', 'suecia'],
    'islandia': ['inglaterra', 'groelandia'],
    'suecia': ['inglaterra', 'moscou'],
    'moscou': ['suecia', 'omsk', 'aral', 'oriente_medio', 'polonia'],
    'omsk': ['moscou', 'aral', 'china', 'mongolia', 'dudinka'],
    'aral': ['moscou', 'oriente_medio', 'india', 'china', 'omsk'],
    'india': ['oriente_medio', 'aral', 'china', 'vietna', 'sumatra'],
    'china': ['aral', 'india', 'vitna', 'japao', 'mongolia', 'omsk', 'tchita', 'vladvostok'],
    'vietna': ['india'],
    'sumatra': ['india', 'australia'],
    'vitna': ['china', 'borneo'],
    'borneo': ['vitna', 'nova_guine', 'australia'],
    'nova_guine': ['borneo', 'australia'],
    'australia': ['borneo', 'sumatra', 'nova_guine'],
    'japao': ['china', 'vladvostok'],
    'mongolia': ['china', 'omsk', 'tchita', 'dudinka'],
    'tchita': ['china', 'mongolia', 'dudinka', 'vladvostok', 'siberia'],
    'dudinka': ['mongolia', 'tchita', 'siberia', 'omsk'],
    'siberia': ['tchita', 'vladvostok', 'dudinka']
}
acoes = ["fort", "atac", "desl"]